# from https://github.com/purescript-halogen/purescript-halogen/blob/master/.github/workflows/ci.yml

name: CI

on:
  push:
    branches: '*'
  pull_request:
    paths-ignore: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.13.8"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output
      - run: npm i -g bower pulp

      - run: bower install

      - run: pulp test
